// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/jaresty/concourse-tracker-bot/status_groomer"
)

type FakeConcourseClient struct {
	GetJobURLsStub        func(string, string) ([]string, error)
	getJobURLsMutex       sync.RWMutex
	getJobURLsArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getJobURLsReturns struct {
		result1 []string
		result2 error
	}
}

func (fake *FakeConcourseClient) GetJobURLs(arg1 string, arg2 string) ([]string, error) {
	fake.getJobURLsMutex.Lock()
	fake.getJobURLsArgsForCall = append(fake.getJobURLsArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.getJobURLsMutex.Unlock()
	if fake.GetJobURLsStub != nil {
		return fake.GetJobURLsStub(arg1, arg2)
	} else {
		return fake.getJobURLsReturns.result1, fake.getJobURLsReturns.result2
	}
}

func (fake *FakeConcourseClient) GetJobURLsCallCount() int {
	fake.getJobURLsMutex.RLock()
	defer fake.getJobURLsMutex.RUnlock()
	return len(fake.getJobURLsArgsForCall)
}

func (fake *FakeConcourseClient) GetJobURLsArgsForCall(i int) (string, string) {
	fake.getJobURLsMutex.RLock()
	defer fake.getJobURLsMutex.RUnlock()
	return fake.getJobURLsArgsForCall[i].arg1, fake.getJobURLsArgsForCall[i].arg2
}

func (fake *FakeConcourseClient) GetJobURLsReturns(result1 []string, result2 error) {
	fake.GetJobURLsStub = nil
	fake.getJobURLsReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

var _ status_groomer.ConcourseClient = new(FakeConcourseClient)
